### ISSUE TITLE
Create Design Drawings and Vote

### ISSUE THREAD

**Issue by fnriv** [Ayaaa99/Winter-Project#1]
Create a drawing of your vision of the website.

- include where features are placed
- this can be multiple photos if there are multiple pages
- feel free to include colors or fonts you want to use
- anything else that helps with your vision :)

Send a screenshot in this issue below and we will vote on **Monday, Jan 29.**

**Comment by fnriv** [comment]
You can add a comment here (press the green comment button) and add your photos and vision!

**Comment by geenalimfat** [comment]
[I Love My Beach.pdf](https://github.com/Ayaaa99/Winter-Project/files/14093202/I.Love.My.Beach.pdf)

**Comment by shrieyaasj** [comment]
![imissmybeach](https://github.com/Ayaaa99/Winter-Project/assets/90736120/0a47e454-3d45-457b-b8d5-de27d8c59c79)

**Comment by Ayaaa99** [comment]
![mybeach1](https://github.com/Ayaaa99/Winter-Project/assets/98358643/97c5507c-1a77-4925-b1c7-7b62072d5944)
![mybeach2](https://github.com/Ayaaa99/Winter-Project/assets/98358643/f176aa59-b2e3-4c62-9439-2909f89ef9fb)
![mybeach3](https://github.com/Ayaaa99/Winter-Project/assets/98358643/e9818e16-2a46-4fd4-b004-8650f57bd8e2)
![mybeach4](https://github.com/Ayaaa99/Winter-Project/assets/98358643/5d55c54e-6e95-43bd-b953-6c0bc63d2735)
![mybeach5](https://github.com/Ayaaa99/Winter-Project/assets/98358643/e8c3ee68-a247-497f-a4d4-2727ea2d061a)

**Comment by fnriv** [comment]
![142 scratch](https://github.com/Ayaaa99/Winter-Project/assets/103224896/cb75ab3f-72be-45b4-900b-501c540f6a62)

**Comment by fnriv** [comment]
<img width="541" alt="Screenshot 2024-02-03 at 10 35 16 AM" src="https://github.com/Ayaaa99/Winter-Project/assets/103224896/ccdb7430-447c-4cbe-aa21-cba021ae490b">

**Comment by geenalimfat** [comment]
![I Miss My Beach-2](https://github.com/Ayaaa99/Winter-Project/assets/114320193/57ad1817-8fc9-49ca-97fd-a54e3343ef0a)
![I Miss My Beach-3](https://github.com/Ayaaa99/Winter-Project/assets/114320193/2d792fa3-0016-4526-bda4-7f96bfb29970)

**Comment by sophiegsmith** [comment]
https://www.canva.com/design/DAF79EW4EPc/ShlsR1kcF_a35ht8JX7hQw/edit?utm_content=DAF79EW4EPc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton


Here are the designs I came up with

**Comment by shrieyaasj** [comment]
![image](https://github.com/Ayaaa99/Winter-Project/assets/90736120/5797c146-cf6d-4f6d-87bd-bdfb0d854c15)

**Comment by fnriv** [comment]
<img width="1180" alt="image" src="https://github.com/Ayaaa99/Winter-Project/assets/103224896/49b79457-c682-4ec7-888d-496efccbfdbb">

**Comment by fnriv** [comment]
layout: 
- todo and spotify on the left
- beach sounds on the right
- timer in center (figure out toggle buttons for reset and such later)
- dark mode, save preferences, and about us in top right
